### ISSUE TITLE
CHANGE VALUES OF VALUES.YAML w/ YQ

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/aws-ec2-vm#12]
```yaml
# example values.yaml
source: github.com/stuttgart-things/aws-ec2-vm
region:
  - eu-west-1
vpc: vpc-08520570421e6f9f4
ami: ami-0cccdaf0d83701c22
itype:
  - t2.micro
  - t3.micro
  - m4.large
publicip: true
secgroupname: terraform-20240325102244051600000002
subnet: subnet-09dd9c1f37ae08fb3
packages:
  - ["wget", "whoami", "chmod", "mv", "update-ca-certificates"]
  - ["vim", "git"]
 ```

sir! @ankitsharma12-ops find a way to change the keys of/to the file with yq. please check for string key, list, and boolean value replacements or additions (list)
